import { Data } from "../UsersExpandableTable";


export const DUMMY_USERS: Data[] = [
    {
        "id": "usr_0001",
        "firstName": "Aftab",
        "lastName": "Ahmed",
        "email": "aftab.ahmed@muslimgive.com",
        "dateOfBirth": "1990-01-15",
        "phoneNumber": "+1 416-555-0101",
        "location": "Toronto, Canada",
        "postalCode": "M5V 2T6",
        "roles": ["Financial Auditor", "Project Manager"],
        "status": "Active",
        "requestingPasswordReset": false
    },
    {
        "id": "usr_0002",
        "firstName": "Fatima",
        "lastName": "Khan",
        "email": "fatima.khan@muslimgive.com",
        "dateOfBirth": "1992-07-22",
        "phoneNumber": "+1 604-555-0102",
        "location": "Vancouver, Canada",
        "postalCode": "V5K 0A1",
        "roles": ["Zakat Auditor"],
        "status": "Active",
        "requestingPasswordReset": true
    },
    {
        "id": "usr_0003",
        "firstName": "Ali",
        "lastName": "Raza",
        "email": "ali.raza@muslimgive.com",
        "dateOfBirth": "1988-03-09",
        "phoneNumber": "+1 403-555-0103",
        "location": "Calgary, Canada",
        "postalCode": "T2P 1J9",
        "roles": ["Operations Manager"],
        "status": "Inactive",
        "requestingPasswordReset": false
    },
    {
        "id": "usr_0004",
        "firstName": "Sara",
        "lastName": "Malik",
        "email": "sara.malik@muslimgive.com",
        "dateOfBirth": "1995-11-02",
        "phoneNumber": "+1 613-555-0104",
        "location": "Ottawa, Canada",
        "postalCode": "K1P 5G4",
        "roles": ["Project Manager", "MG Admin"],
        "status": "Active",
        "requestingPasswordReset": true
    },
    {
        "id": "usr_0005",
        "firstName": "Bilal",
        "lastName": "Hussain",
        "email": "bilal.hussain@muslimgive.com",
        "dateOfBirth": "1991-05-19",
        "phoneNumber": "+1 514-555-0105",
        "location": "Montreal, Canada",
        "postalCode": "H3B 2Y5",
        "roles": ["Financial Auditor"],
        "status": "Active",
        "requestingPasswordReset": false
    },
    {
        "id": "usr_0006",
        "firstName": "Zainab",
        "lastName": "Shaikh",
        "email": "zainab.shaikh@muslimgive.com",
        "dateOfBirth": "1987-09-30",
        "phoneNumber": "+1 780-555-0106",
        "location": "Edmonton, Canada",
        "postalCode": "T5J 1N9",
        "roles": ["MG Admin", "Operations Manager"],
        "status": "Inactive",
        "requestingPasswordReset": false
    },
    {
        "id": "usr_0007",
        "firstName": "Hamza",
        "lastName": "Butt",
        "email": "hamza.butt@muslimgive.com",
        "dateOfBirth": "1993-12-10",
        "phoneNumber": "+1 204-555-0107",
        "location": "Winnipeg, Canada",
        "postalCode": "R3C 1A6",
        "roles": ["Project Manager"],
        "status": "Active",
        "requestingPasswordReset": false
    },
    {
        "id": "usr_0008",
        "firstName": "Noor",
        "lastName": "Javed",
        "email": "noor.javed@muslimgive.com",
        "dateOfBirth": "1996-04-07",
        "phoneNumber": "+1 418-555-0108",
        "location": "Quebec City, Canada",
        "postalCode": "G1R 2K9",
        "roles": ["Zakat Auditor", "Financial Auditor"],
        "status": "Active",
        "requestingPasswordReset": false
    },
    {
        "id": "usr_0009",
        "firstName": "Usman",
        "lastName": "Iqbal",
        "email": "usman.iqbal@muslimgive.com",
        "dateOfBirth": "1989-02-25",
        "phoneNumber": "+1 902-555-0109",
        "location": "Halifax, Canada",
        "postalCode": "B3J 3K5",
        "roles": ["Operations Manager"],
        "status": "Inactive",
        "requestingPasswordReset": false
    },
    {
        "id": "usr_0010",
        "firstName": "Maryam",
        "lastName": "Yousaf",
        "email": "maryam.yousaf@muslimgive.com",
        "dateOfBirth": "1994-06-18",
        "phoneNumber": "+1 306-555-0110",
        "location": "Saskatoon, Canada",
        "postalCode": "S7K 3J8",
        "roles": ["Project Manager", "MG Admin"],
        "status": "Active",
        "requestingPasswordReset": false
    },
    {
        "id": "usr_0011",
        "firstName": "Danish",
        "lastName": "Siddiqui",
        "email": "danish.siddiqui@muslimgive.com",
        "dateOfBirth": "1986-08-11",
        "phoneNumber": "+1 306-555-0111",
        "location": "Regina, Canada",
        "postalCode": "S4P 3X1",
        "roles": ["Financial Auditor"],
        "status": "Active",
        "requestingPasswordReset": false
    },
    {
        "id": "usr_0012",
        "firstName": "Hira",
        "lastName": "Qureshi",
        "email": "hira.qureshi@muslimgive.com",
        "dateOfBirth": "1997-10-03",
        "phoneNumber": "+1 250-555-0112",
        "location": "Victoria, Canada",
        "postalCode": "V8W 1L7",
        "roles": ["Zakat Auditor"],
        "status": "Inactive",
        "requestingPasswordReset": false
    },
    {
        "id": "usr_0013",
        "firstName": "Saad",
        "lastName": "Farooq",
        "email": "saad.farooq@muslimgive.com",
        "dateOfBirth": "1990-05-05",
        "phoneNumber": "+1 905-555-0113",
        "location": "Brampton, Canada",
        "postalCode": "L6Y 4R2",
        "roles": ["Operations Manager", "MG Admin"],
        "status": "Active",
        "requestingPasswordReset": false
    },
    {
        "id": "usr_0014",
        "firstName": "Ayesha",
        "lastName": "Tariq",
        "email": "ayesha.tariq@muslimgive.com",
        "dateOfBirth": "1998-01-27",
        "phoneNumber": "+1 905-555-0114",
        "location": "Mississauga, Canada",
        "postalCode": "L5B 2C9",
        "roles": ["Project Manager"],
        "status": "Active",
        "requestingPasswordReset": false
    },
    {
        "id": "usr_0015",
        "firstName": "Rizwan",
        "lastName": "Sheikh",
        "email": "rizwan.sheikh@muslimgive.com",
        "dateOfBirth": "1985-12-21",
        "phoneNumber": "+1 519-555-0115",
        "location": "Kitchener, Canada",
        "postalCode": "N2G 1H6",
        "roles": ["Financial Auditor", "Zakat Auditor"],
        "status": "Inactive",
        "requestingPasswordReset": false
    }
]
